// Refer https://pre-commit.com/#install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-json
    - id: pretty-format-json
      args: [--autofix]
    - id: check-merge-conflict
    - id: check-symlinks
    - id: detect-private-key
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: check-toml
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
    - id: cargo-check
    - id: clippy
