
//! Autogenerated weights for pallet_rmrk_market
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-16, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Joshuas-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/rmrk-substrate
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_rmrk_market
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/rmrk-market/src/weights.rs
// --template
// ./benchmarking/frame-weight-template.hbs
// --detailed-log-output

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_rmrk_market.
pub trait WeightInfo {
	fn buy() -> Weight;
	fn list() -> Weight;
	fn unlist() -> Weight;
	fn make_offer() -> Weight;
	fn withdraw_offer() -> Weight;
	fn accept_offer() -> Weight;
}

/// Weights for pallet_rmrk_market using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Uniques Asset (r:1 w:1)
	// Storage: RmrkMarket ListedNfts (r:1 w:1)
	// Storage: RmrkCore Nfts (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Uniques Class (r:1 w:0)
	// Storage: RmrkCore Lock (r:0 w:1)
	// Storage: Uniques Account (r:0 w:2)
	// Storage: Uniques ItemPriceOf (r:0 w:1)
	fn buy() -> Weight {
		// Minimum execution time: 73_000 nanoseconds.
		Weight::from_ref_time(74_000_000)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	// Storage: Uniques Asset (r:1 w:0)
	// Storage: RmrkCore Nfts (r:1 w:0)
	// Storage: Uniques Class (r:1 w:0)
	// Storage: RmrkCore Lock (r:1 w:1)
	// Storage: RmrkMarket ListedNfts (r:0 w:1)
	fn list() -> Weight {
		// Minimum execution time: 29_000 nanoseconds.
		Weight::from_ref_time(30_000_000)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: RmrkMarket ListedNfts (r:1 w:1)
	// Storage: Uniques Asset (r:1 w:0)
	// Storage: RmrkCore Lock (r:0 w:1)
	fn unlist() -> Weight {
		// Minimum execution time: 23_000 nanoseconds.
		Weight::from_ref_time(23_000_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Uniques Asset (r:1 w:0)
	// Storage: RmrkMarket Offers (r:1 w:1)
	fn make_offer() -> Weight {
		// Minimum execution time: 32_000 nanoseconds.
		Weight::from_ref_time(32_000_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: RmrkMarket Offers (r:1 w:1)
	// Storage: Uniques Asset (r:1 w:0)
	fn withdraw_offer() -> Weight {
		// Minimum execution time: 32_000 nanoseconds.
		Weight::from_ref_time(32_000_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Uniques Asset (r:1 w:1)
	// Storage: RmrkMarket Offers (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: RmrkCore Nfts (r:1 w:1)
	// Storage: Uniques Class (r:1 w:0)
	// Storage: RmrkCore Lock (r:0 w:1)
	// Storage: Uniques Account (r:0 w:2)
	// Storage: Uniques ItemPriceOf (r:0 w:1)
	fn accept_offer() -> Weight {
		// Minimum execution time: 87_000 nanoseconds.
		Weight::from_ref_time(88_000_000)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(8))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Uniques Asset (r:1 w:1)
	// Storage: RmrkMarket ListedNfts (r:1 w:1)
	// Storage: RmrkCore Nfts (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Uniques Class (r:1 w:0)
	// Storage: RmrkCore Lock (r:0 w:1)
	// Storage: Uniques Account (r:0 w:2)
	// Storage: Uniques ItemPriceOf (r:0 w:1)
	fn buy() -> Weight {
		// Minimum execution time: 73_000 nanoseconds.
		Weight::from_ref_time(74_000_000)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
	// Storage: Uniques Asset (r:1 w:0)
	// Storage: RmrkCore Nfts (r:1 w:0)
	// Storage: Uniques Class (r:1 w:0)
	// Storage: RmrkCore Lock (r:1 w:1)
	// Storage: RmrkMarket ListedNfts (r:0 w:1)
	fn list() -> Weight {
		// Minimum execution time: 29_000 nanoseconds.
		Weight::from_ref_time(30_000_000)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	// Storage: RmrkMarket ListedNfts (r:1 w:1)
	// Storage: Uniques Asset (r:1 w:0)
	// Storage: RmrkCore Lock (r:0 w:1)
	fn unlist() -> Weight {
		// Minimum execution time: 23_000 nanoseconds.
		Weight::from_ref_time(23_000_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	// Storage: Uniques Asset (r:1 w:0)
	// Storage: RmrkMarket Offers (r:1 w:1)
	fn make_offer() -> Weight {
		// Minimum execution time: 32_000 nanoseconds.
		Weight::from_ref_time(32_000_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: RmrkMarket Offers (r:1 w:1)
	// Storage: Uniques Asset (r:1 w:0)
	fn withdraw_offer() -> Weight {
		// Minimum execution time: 32_000 nanoseconds.
		Weight::from_ref_time(32_000_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	// Storage: Uniques Asset (r:1 w:1)
	// Storage: RmrkMarket Offers (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: RmrkCore Nfts (r:1 w:1)
	// Storage: Uniques Class (r:1 w:0)
	// Storage: RmrkCore Lock (r:0 w:1)
	// Storage: Uniques Account (r:0 w:2)
	// Storage: Uniques ItemPriceOf (r:0 w:1)
	fn accept_offer() -> Weight {
		// Minimum execution time: 87_000 nanoseconds.
		Weight::from_ref_time(88_000_000)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
}